version: "3.7"
services:

  trendyol-database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trendyol
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

  trendyol-link-converter:
    image: ogedik/trendyol-link-converter:0.0.1-SNAPSHOT
    depends_on:
      - trendyol-database
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: trendyol-database
      DATABASE_PORT: 3306
      DATABASE_NAME: trendyol
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root